# -*- mode: python ; coding: utf-8 -*-
# tubelm_win.spec — Windows PyInstaller spec for TubeLM
# Entry point: win_launcher.py (system tray + Flask GUI)
# Run from desktop/ directory: pyinstaller --clean tubelm_win.spec

a = Analysis(
    ['win_launcher.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('../.env.example', '.'),
        ('../channels.json.example', '.'),
        ('templates', 'templates'),
        ('../shared/assets', 'assets'),
        ('../shared/prompts/Summary_Prompt.md', '.'),
        ('../shared/prompts/Podcast_Prompt.md', '.'),
    ],
    hiddenimports=[
        # ── Local application modules ───────────────────────────────────────────
        'config',
        'gui',
        'main',
        'paths',
        'email_service',
        'notebooklm_service',
        # ── Core pipeline dependencies ─────────────────────────────────────────
        'rookiepy',
        'feedparser',
        'sgmllib',
        'sgmllib3k',
        'markdown_it',
        'markdown_it.main',
        'markdown_it.ruler',
        'markdown_it.utils',
        'markdown_it.token',
        'markdown_it.parser_block',
        'markdown_it.parser_core',
        'markdown_it.parser_inline',
        'markdown_it.renderer',
        'mdurl',
        'dotenv',
        # ── notebooklm-py internals ────────────────────────────────────────────
        'notebooklm',
        'notebooklm._core',
        'notebooklm._settings',
        'notebooklm.auth',
        'notebooklm.paths',
        'notebooklm.exceptions',
        'notebooklm.cli',
        'notebooklm.cli.services',
        'notebooklm.cli.services.login',
        'notebooklm.cli.services.login.refresh',
        # ── HTTP stack ────────────────────────────────────────────────────────
        'httpx',
        'httpcore',
        'httpcore._sync',
        'httpcore._sync.http11',
        'httpcore._sync.http2',
        'httpcore._sync.connection',
        'httpcore._sync.connection_pool',
        'httpcore._async',
        'httpcore._async.http11',
        'httpcore._async.http2',
        'httpcore._async.connection',
        'httpcore._async.connection_pool',
        'h11',
        'anyio',
        'anyio._backends',
        'anyio._backends._asyncio',
        'anyio._core',
        'anyio._core._fileio',
        'anyio._core._sockets',
        'anyio._core._subprocesses',
        'sniffio',
        # ── Flask and web stack ────────────────────────────────────────────────
        'flask',
        'werkzeug',
        'werkzeug.serving',
        'werkzeug.debug',
        'jinja2',
        'jinja2.ext',
        'markupsafe',
        'itsdangerous',
        'click',
        'blinker',
        # ── Email ─────────────────────────────────────────────────────────────
        'smtplib',
        'email',
        'email.mime',
        'email.mime.multipart',
        'email.mime.text',
        'email.mime.image',
        # ── System tray (Windows — pystray + Pillow) ───────────────────────────
        'pystray',
        'pystray._win32',
        'PIL',
        'PIL.Image',
        'PIL.ImageDraw',
        'PIL.ImageFont',
        # ── Playwright ────────────────────────────────────────────────────────
        'playwright',
        'playwright.sync_api',
        'playwright._impl',
        'playwright._impl._driver',
        'playwright._impl._api_types',
        'playwright._impl._browser',
        'pyee',
        'pyee.base',
        # ── Async runtime ─────────────────────────────────────────────────────
        'asyncio',
        'asyncio.events',
        'asyncio.tasks',
        'asyncio.futures',
        'concurrent.futures',
        # ── Stdlib / HTTP utilities ────────────────────────────────────────────
        'importlib.metadata',
        'pkg_resources',
        'certifi',
        'charset_normalizer',
        'idna',
        'urllib3',
        'requests',
        'requests.adapters',
        'requests.auth',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        # Exclude Linux-only and macOS-only modules
        'rumps',
        'Xlib',
    ],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='TubeLM',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=['../shared/assets/logo.ico'],
)
coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='TubeLM',
)
